### ISSUE TITLE
Preliminary API requirements

### ISSUE THREAD

**Issue by yinghuaguan** [OpenDRR/opendrr-api#1]
The API for maps needs to be able to accept:
- Aggregation/Zoom level
- Risk Metrics
- ~~Map centre coordinates~~
- User viewport dimensions (returning only results within the viewport viewable area)
- a search query that will re-centre the map on the first search result

for charts:
- an array of metrics 
- feature IDs  

We will develop an example API response for maps and charts for ingestion into leaflet and d3 once we have the sample data in hand.

**Comment by jvanulde** [comment]
Is it necessary for the API to filter on map centre coordinates? Generally, the viewport (aka bounding box or bbox) is sent to an API and it returns the items that intersect with it. If you want a single feature you just dereference the resource direction (e.g. ...api/items/my-feature-id).

**Comment by yinghuaguan** [comment]
@jvanulde Yes, you are right. we could do it by bounding box.

**Comment by jvanulde** [comment]
Also, the requirement for "a search query that will re-centre the map on the first search result" can be done on the client. The API returns items and the UI takes the first item. Ideally, the UI will send a request for a limit of 1 item that may or may not include a sort.

**Comment by jvanulde** [comment]
Closing. Further work via #14
