### ISSUE TITLE
Store all province PSRA indicators in single ElasticSearch index

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/opendrr-api#103]
PSRA indicators are stored by province in PostGIS for computational reasons. 

it would be cleaner to group all P/Ts into a single Sauid and Building PSRA index

**Comment by wkhchow** [comment]
just saw this issue.  
You can check the db, i already generated a table/view that combines all the psra indicators in _b/_s.  Check the results_psra_national schema and can potentially just convert that piece to ES index.
