### ISSUE TITLE
Mapping exists but property is absent

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/opendrr-api#130]
https://github.com/OpenDRR/opendrr-api/blob/71cc17116b5473b3e6ab1c380081375d407b6ca0/python/exposure_postgres2es.py#L67

For the Geotile Aggregations to work it appears that we need to have the coordinates property. The mapping exists but the property is not added. Can we add this?

**Comment by jvanulde** [comment]
Actually, we can use a geo_shape field (i.e. geometry) which we have in the indices already. Can we remove the `coordinates` mapping?

**Comment by drotheram** [comment]
We map the Sauid polygons as geo_shape but the building level aggregation are point geometries that we would like to reflect in the index geometry

**Comment by jvanulde** [comment]
> I've found that: ` 'mappings': { 'properties': { 'geometry': { 'properties': { 'coordinates':{ 'type': 'geo_point' } } } }`
> 
> Works for Kibana's grid tile aggregation. We can only do geom_poly aggregations with the "Gold" license

Can we close this then?

**Comment by drotheram** [comment]
Yes, this issue is resolved.
