### ISSUE TITLE
Fetch dependencies (e.g. model-factory) as release assets to avoid the use of git clone

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/opendrr-api#155]
_Originally posted by @jvanulde in https://github.com/OpenDRR/opendrr-api/pull/154#discussion_r788024086_:

> Can we move the dependencies to release assets to avoid a clone?

@jvanulde Intriguing idea!  (I've never thought of this before, at least not for model-factory, as I was only thinking of a way out of Git LFS and model-factory doesn't use any and escaped my mind)

But yeah!  This would be one way to ensure the versions are consistent between model-factory and opendrr-api for releases, and we do get the "Source code (tar.gz)" release assets for free, automatically generated by GitHub whenever version is tagged and/or released, e.g. https://github.com/OpenDRR/model-factory/archive/refs/tags/v1.2.0.tar.gz

For development (and testing), I guess we could keep the alternative of using `git clone` to fetch from `master` or topic branch like `update_dsra_psra_oct2021`, though apparently we could just fetch these as tarballs too unless we need the git history:

* https://github.com/OpenDRR/model-factory/archive/refs/heads/master.tar.gz
* https://github.com/OpenDRR/model-factory/archive/refs/heads/update_dsra_psra_oct2021.tar.gz

Interesting!  Let the discussion begin!

**Comment by jvanulde** [comment]
This shouldn't block #154 we can address later.

**Comment by anthonyfok** [comment]
In retrospect, my original title of this issue "Fetch dependencies (e.g. model-factory) as release assets to avoid the use of git clone" was a bit of a misnomer, so I have adjusted the title to match @drotheram's excellent fix in PR #156.

* #156

For replacing expensive Git LFS pulls with release assets downloads from OpenDRR/canada-srm2, OpenDRR/earthquake-scenarios, etc., see Issue #190:

* #190
