### ISSUE TITLE
Null values in results_nhsl_physical_exposure.nhsl_physical_exposure_indicators_hexbin_global_fabric

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/opendrr-api#165]
![Screen Shot 2022-02-04 at 4 49 38 PM](https://user-images.githubusercontent.com/7228960/152621589-bb06bbe2-e95a-4cbe-8530-7ce0866ad6d2.png)

**Comment by wkhchow** [comment]
Investigating

**Comment by wkhchow** [comment]
Null values showing up because of the precision of the global fabric hexbin.  over 4000 SA's along the coastline does not intersect with the hexgrid.  Solution is to update new intersect table and attach nearest hexbin to the 4000 SA's

**Comment by wkhchow** [comment]
fixed in newest boundaries version
