### ISSUE TITLE
Building Level Geohashes produced by PostGIS not parsed properly by ES/Kibana

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/opendrr-api#17]
The geohash strings generated by PostGIS representing point locations are not parsed by ES/Kibana as locations. Spatial queries based on locations return empty responses. 

This is not an issue for the Sauid geometries which are represented by polygons instead of points.

**Comment by jvanulde** [comment]
@drotheram is this still a problem? Please close if resolved.

**Comment by drotheram** [comment]
Resolved with revised index mapping
