### ISSUE TITLE
update opendrr.config.yml to handle v1.4.0 indices

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/opendrr-api#192]
PygeoAPI records pointing to old versions of indices

Need to update:
https://github.com/OpenDRR/opendrr-api/blob/master/pygeoapi/opendrr.config.yml

to point to latest version of indices. Ideally automate the yml generation script with a version argument to ease future updates to versions

**Comment by jvanulde** [comment]
There is a version argument now in the config. I think we can close this @drotheram.

**Comment by drotheram** [comment]
Agreed, We can close this now
