### ISSUE TITLE
Add intersecting features fix to python container in docker-compose

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/opendrr-api#20]
We need to run the following `psql` query:

    UPDATE boundaries."Geometry SAUID" SET geom = ST_MakeValid(geom);

**Comment by wkhchow** [comment]
If i recall correctly the only offending geometries were the SAUID.  The other geometries are there for reference and do not get called upon for any of the views.

**Comment by jvanulde** [comment]
@wkhchow was this addressed in https://github.com/OpenDRR/boundaries/pull/2?

**Comment by jvanulde** [comment]
Fixed in https://github.com/OpenDRR/opendrr-data-store/commit/0e6f0af4c6a662c08a3e46c68cc1e4ae2e83c037
