### ISSUE TITLE
Mismatch between hexgrid tables in postgis and hexgrid_{}km_postgres2es.py loading scripts

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/opendrr-api#205]
psycopg2.errors.UndefinedTable: relation "boundaries.HexGrid_100km" does not exist
LINE 1: ...CT *, ST_AsGeoJSON(geom)                     FROM boundaries...

**Comment by wkhchow** [comment]
fix will be implemented in newest version (v1.4.2)
