### ISSUE TITLE
Some SQL scripts called by add_data.sh do not CASCADE their DROP commands

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/opendrr-api#22]
This causes add_data.sh to fail when re-running if the database already contains tables or views that are dependent on tables subject to DROP commands when CASCADE is not included.

**Comment by jvanulde** [comment]
@wkhchow @drotheram is this issue best addressed in https://github.com/OpenDRR/opendrr-data-store repo? We should indicate the script(s) that are implicated. I'm moving to current Sprint.

**Comment by jvanulde** [comment]
@drotheram @wkhchow any progress on this? Should we park it?

**Comment by drotheram** [comment]
We haven't attacked it yet but thanks for highlighting. This is an active issue when we try to re-run the python container after the build has completed.

**Comment by wkhchow** [comment]
Added CASCADE to all DROPs in model factory and other scripts going forward.
