### ISSUE TITLE
Look into ways to sync PostGIS with Elasticsearch

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/opendrr-api#5]
We need to synchronize PostGIS with Elasticsearch. This need to be done when data in updated in PostGIS. Maybe we look at LogStash?

**Comment by jvanulde** [comment]
@drotheram if we implement Tom's scripts we should be close to what we need. Where this process runs in the future remains to be seen but for now a manual "push" to ES is sufficient.

**Comment by jvanulde** [comment]
@drotheram can we close this?

**Comment by drotheram** [comment]
Yes, we have demonstrated in: https://github.com/OpenDRR/opendrr-api/tree/postgis-sync
