### ISSUE TITLE
add_data.sh - curl commands

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/opendrr-api#66]
Verify downloads have completed without errors, otherwise retry downloads

**Comment by anthonyfok** [comment]
Ideas:

1. According to https://unix.stackexchange.com/questions/287431/continue-interrupted-curl-download, we can use something like:

         curl -L -O --retry 999 --retry-max-time 0 -C - http://url

2. Having some kind of checksum mechanism, e.g. sha256sum, or even with GPG signature, would be nice.

Pending on completion of https://github.com/OpenDRR/opendrr-api/pull/68, i.e. after we have moved the multiple curl calls to its own function.

**Comment by anthonyfok** [comment]
Notes to self:

* Check for type: `file` vs `dir`
* `--no-act` or `--dry-run` or something similar for add_data.sh to "predict" how much files would be downloaded before download.

* Use a repo for cache?
    * Encrypted, compressed cached private data on a public repo?
    * (see if the compressed files are small enough to avoid Git LFS altogether.)

**Comment by jvanulde** [comment]
@anthonyfok are we moving to Sprint 31?

**Comment by anthonyfok** [comment]
PR #82 partly solves this issue, but not quite.  Please see follow-up issues #83 and #90.
