### ISSUE TITLE
opendrr-api - investigate index mapping in pygeoapi

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/opendrr-api#69]
Index mapping is not explicitly defined beyond the point or polygon geometries. pygeoapi automatically defines an incorrect mapping. We need to investigate ways to explicitly define a mapping while loading indices into ES so that the full suite of properties is visible in pygeoapi

**Comment by jvanulde** [comment]
@drotheram has this been resolved?

**Comment by drotheram** [comment]
I believe this is still an open issue, distinct from the geospatial mappings

**Comment by jvanulde** [comment]
@drotheram is this more or less addressed now?

**Comment by drotheram** [comment]
Yes, we can close this now
