### ISSUE TITLE
import new hexbin geometries

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/opendrr-api#85]
- need to modify add_data.sh to import new additional hexbin geometries for testing from the boundaries repo (5km, 10km, 25km, 50km, sauid_hexgrid) 

- [ ] add in add_data.sh
- [ ] add indexes to ES

**Comment by wkhchow** [comment]
New branch is created to import the new hexbin geometries.  https://github.com/OpenDRR/opendrr-api/tree/update_hexbin_geometry

Are you guys able to modify the add_data.sh to incorporate the hexbin geometries in the boundaries repo 
https://github.com/OpenDRR/boundaries/tree/master/hexbin_4326 in the run_ogr2ogr function? @anthonyfok 

Don't think the load ES for boundaries is in yet.  This might be the good time to incorporate that piece including the hexbins? @drotheram

**Comment by anthonyfok** [comment]
@wkhchow Thanks for the note!  I do need to modify the GitHub workflow YAML file over at OpenDRR/boundaries to process the hexbin subdirectory and upload the files therein too.  I'll follow up over in that repo.

**Comment by wkhchow** [comment]
https://github.com/OpenDRR/opendrr-api/tree/import_hexbin_geometries

**Comment by anthonyfok** [comment]
I'll have a go at this, especially now I realized that the way I originally wrote run_ogr2ogr function actually added complications to this.  I'd better fix my own bug, hehe.
